import datetime
import re

class RuleGenerator:
    """
    Generate YARA rules from scored strings.
    """

    def __init__(self, rule_name="AutoGeneratedRule", author="Analyst"):
        self.rule_name = self.sanitize_rule_name(rule_name)
        self.author = author

    # **************** SANITIZE ***********************************
    def sanitize_rule_name(self, name: str) -> str:
        return re.sub(r"\W+", "_", name)

    # ***************** ESCAPE ************************************
    def escape_string(self, s: str) -> str:
        return s.replace("\\", "\\\\").replace('"', '\\"')

    # ***************** SELECT STRINGS ****************************
    def select_strings(self, scored_strings, max_strings=20):
        selected = []

        for s, score in scored_strings:
            if score < 3:
                continue

            selected.append(s)

            if len(selected) >= max_strings:
                break

        # fallback
        if len(selected) < 3:
            selected = [s for s, _ in scored_strings[:min(10, max_strings)]]

        return selected

    # **************** DETECT TYPE ************************
    def detect_type(self, s: str) -> str:
        s_lower = s.lower()

        if "http" in s_lower:
            return "url"
        if "cmd" in s_lower or "powershell" in s_lower:
            return "command"
        if "hkey" in s_lower:
            return "registry"
        if ".dll" in s_lower:
            return "dll"
        if ".exe" in s_lower:
            return "exe"
        return "other"

    #******************* BUILD STRINGS **************************
    def build_strings_section(self, strings):
        """string modifiers in YARA """
        yara_strings = []

        for i, s in enumerate(strings):
            escaped = self.escape_string(s)
            modifiers = ""

            s_lower = s.lower()

            if s_lower.startswith("http"):
                modifiers = " nocase ascii"

            elif ".exe" in s_lower or ".dll" in s_lower:
                modifiers = " ascii wide"

            elif "cmd" in s_lower or "powershell" in s_lower:
                modifiers = " nocase"

            yara_strings.append(f'        $s{i+1} = "{escaped}"{modifiers}')

        return "\n".join(yara_strings)

    # ********************** CONDITION ********************************
    def build_condition(self, count):
        if count == 0:
            return "false"
        elif count == 1:
            return "$s1"
        elif count <= 3:
            return "any of them"
        else:
            return f"{count // 2} of them"

    # ************************ GENERATE RULE ****************************
    def generate_rule(self, scored_strings):
        try:
            selected = self.select_strings(scored_strings)

            strings_section = self.build_strings_section(selected)
            condition = self.build_condition(len(selected))

            date = datetime.datetime.now().strftime("%Y-%m-%d")

            escaped_author = self.escape_string(self.author)

            rule = f"""
rule {self.rule_name}
{{
    meta:
        author = "{escaped_author}"
        date = "{date}"
        description = "Auto-generated rule from Smart YARA tool"

    strings:
{strings_section}

    condition:
        {condition}
}}
"""
            return rule.strip()

        except Exception as e:
            return f"/* ERROR: {str(e)} */"
